create extension if not exists pg_trgm with schema extensions;

create table if not exists public.taco_import_batches (
  id uuid primary key default gen_random_uuid(),
  source_name text not null,
  source_edition text not null,
  publication_year smallint not null check (publication_year between 1900 and 2100),
  source_url text not null,
  source_file_name text not null,
  source_file_sha256 text not null check (source_file_sha256 ~ '^[0-9a-f]{64}$'),
  reference_basis text not null default '100 g de parte comestível',
  food_count integer not null default 0 check (food_count >= 0),
  nutrient_value_count integer not null default 0 check (nutrient_value_count >= 0),
  imported_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (source_name, source_edition, source_file_sha256)
);

alter table public.taco_foods
  add column if not exists source_edition text,
  add column if not exists publication_year smallint,
  add column if not exists source_url text,
  add column if not exists reference_quantity_g numeric,
  add column if not exists reference_basis text,
  add column if not exists source_key text,
  add column if not exists import_batch_id uuid references public.taco_import_batches(id) on delete set null;

update public.taco_foods
set
  source_edition = coalesce(source_edition, '4ª edição ampliada e revisada'),
  publication_year = coalesce(publication_year, 2011),
  source_url = coalesce(
    source_url,
    'https://nepa.unicamp.br/wp-content/uploads/sites/27/2023/10/Taco-4a-Edicao.xlsx'
  ),
  reference_quantity_g = coalesce(reference_quantity_g, 100),
  reference_basis = coalesce(reference_basis, '100 g de parte comestível'),
  source_key = coalesce(
    source_key,
    concat('TACO:2011:', coalesce(code, normalized_name, id::text))
  );

alter table public.taco_foods
  alter column source_edition set not null,
  alter column publication_year set not null,
  alter column source_url set not null,
  alter column reference_quantity_g set not null,
  alter column reference_basis set not null,
  alter column source_key set not null;

alter table public.taco_foods
  alter column source_edition set default '4ª edição ampliada e revisada',
  alter column publication_year set default 2011,
  alter column source_url set default 'https://nepa.unicamp.br/wp-content/uploads/sites/27/2023/10/Taco-4a-Edicao.xlsx',
  alter column reference_quantity_g set default 100,
  alter column reference_basis set default '100 g de parte comestível';

alter table public.taco_foods
  drop constraint if exists taco_foods_publication_year_check,
  add constraint taco_foods_publication_year_check
    check (publication_year between 1900 and 2100),
  drop constraint if exists taco_foods_reference_quantity_g_check,
  add constraint taco_foods_reference_quantity_g_check
    check (reference_quantity_g > 0);

create unique index if not exists taco_foods_source_key_unique
  on public.taco_foods (source_key);

alter table public.taco_foods
  add column if not exists search_document tsvector
  generated always as (
    to_tsvector(
      'portuguese'::regconfig,
      coalesce(name, '') || ' ' || coalesce(search_name, '') || ' ' || coalesce(category, '')
    )
  ) stored;

drop index if exists public.idx_taco_foods_name;
create index if not exists taco_foods_search_document_idx
  on public.taco_foods using gin (search_document);
create index if not exists taco_foods_normalized_name_trgm_idx
  on public.taco_foods using gin (normalized_name extensions.gin_trgm_ops);

create table if not exists public.taco_food_nutrients (
  id bigint generated by default as identity primary key,
  food_id uuid not null references public.taco_foods(id) on delete cascade,
  nutrient_code text not null,
  nutrient_name text not null,
  amount numeric,
  unit text not null,
  value_status text not null,
  source_value text,
  source_sheet text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint taco_food_nutrients_code_check
    check (nutrient_code ~ '^[a-z0-9_:-]+$'),
  constraint taco_food_nutrients_status_check
    check (value_status in ('measured', 'trace', 'not_applicable', 'not_analyzed', 'missing')),
  constraint taco_food_nutrients_amount_check
    check (amount is null or amount >= 0),
  unique (food_id, nutrient_code)
);

create index if not exists taco_food_nutrients_food_id_idx
  on public.taco_food_nutrients (food_id);
create index if not exists taco_food_nutrients_code_food_idx
  on public.taco_food_nutrients (nutrient_code, food_id);

drop trigger if exists taco_food_nutrients_updated_at on public.taco_food_nutrients;
create trigger taco_food_nutrients_updated_at
before update on public.taco_food_nutrients
for each row execute function public.update_updated_at_column();

alter table public.taco_import_batches enable row level security;
alter table public.taco_food_nutrients enable row level security;

drop policy if exists "Authenticated users read TACO nutrients" on public.taco_food_nutrients;
create policy "Authenticated users read TACO nutrients"
on public.taco_food_nutrients
for select
to authenticated
using ((select auth.uid()) is not null and (select private.password_change_complete()));

revoke all on table public.taco_import_batches from anon, authenticated;
revoke all on table public.taco_food_nutrients from anon, authenticated;
grant select on table public.taco_food_nutrients to authenticated;
grant all on table public.taco_import_batches to service_role;
grant all on table public.taco_food_nutrients to service_role;
revoke all on sequence public.taco_food_nutrients_id_seq from anon, authenticated;
grant usage, select on sequence public.taco_food_nutrients_id_seq to service_role;

-- TACO is reference data. Clients may read it, but only the trusted importer may mutate it.
revoke all on table public.taco_foods from anon, authenticated;
grant select on table public.taco_foods to authenticated;
grant all on table public.taco_foods to service_role;

create or replace function public.normalize_taco_search_text(value text)
returns text
language sql
immutable
parallel safe
set search_path = ''
as $$
  select trim(
    regexp_replace(
      translate(
        lower(coalesce(value, '')),
        'áàâãäéèêëíìîïóòôõöúùûüçñ',
        'aaaaaeeeeiiiiooooouuuucn'
      ),
      '[^a-z0-9]+',
      ' ',
      'g'
    )
  );
$$;

create or replace function public.search_taco_foods(
  p_query text default '',
  p_category text default null,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id uuid,
  code text,
  name text,
  search_name text,
  normalized_name text,
  category text,
  moisture_g numeric,
  energy_kcal numeric,
  energy_kj numeric,
  protein_g numeric,
  lipid_g numeric,
  cholesterol_mg numeric,
  carbohydrate_g numeric,
  fiber_g numeric,
  ash_g numeric,
  calcium_mg numeric,
  magnesium_mg numeric,
  manganese_mg numeric,
  phosphorus_mg numeric,
  iron_mg numeric,
  sodium_mg numeric,
  potassium_mg numeric,
  copper_mg numeric,
  zinc_mg numeric,
  retinol_mcg numeric,
  re_mcg numeric,
  rae_mcg numeric,
  thiamine_mg numeric,
  riboflavin_mg numeric,
  pyridoxine_mg numeric,
  niacin_mg numeric,
  vitamin_c_mg numeric,
  source text,
  source_edition text,
  publication_year smallint,
  source_url text,
  reference_quantity_g numeric,
  reference_basis text,
  match_kind text,
  relevance real,
  total_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  with input as (
    select
      public.normalize_taco_search_text(p_query) as normalized_query,
      case
        when nullif(trim(coalesce(p_query, '')), '') is null then null
        else pg_catalog.websearch_to_tsquery('portuguese'::regconfig, p_query)
      end as text_query
  ),
  ranked as (
    select
      food.*,
      case
        when input.normalized_query = '' then 'browse'
        when food.normalized_name = input.normalized_query then 'exact'
        when food.normalized_name like input.normalized_query || '%' then 'prefix'
        when food.search_document @@ input.text_query then 'full_text'
        else 'similar'
      end as match_kind,
      case
        when input.normalized_query = '' then 0::real
        when food.normalized_name = input.normalized_query then 100::real
        when food.normalized_name like input.normalized_query || '%' then 80::real
        when food.search_document @@ input.text_query
          then (50 + 10 * pg_catalog.ts_rank(food.search_document, input.text_query))::real
        else (30 * extensions.similarity(food.normalized_name, input.normalized_query))::real
      end as relevance
    from public.taco_foods as food
    cross join input
    where
      (p_category is null or food.category = p_category)
      and (
        input.normalized_query = ''
        or food.normalized_name = input.normalized_query
        or food.normalized_name like input.normalized_query || '%'
        or food.search_document @@ input.text_query
        or food.normalized_name operator(extensions.%) input.normalized_query
      )
  )
  select
    ranked.id, ranked.code, ranked.name, ranked.search_name, ranked.normalized_name,
    ranked.category, ranked.moisture_g, ranked.energy_kcal, ranked.energy_kj,
    ranked.protein_g, ranked.lipid_g, ranked.cholesterol_mg, ranked.carbohydrate_g,
    ranked.fiber_g, ranked.ash_g, ranked.calcium_mg, ranked.magnesium_mg,
    ranked.manganese_mg, ranked.phosphorus_mg, ranked.iron_mg, ranked.sodium_mg,
    ranked.potassium_mg, ranked.copper_mg, ranked.zinc_mg, ranked.retinol_mcg,
    ranked.re_mcg, ranked.rae_mcg, ranked.thiamine_mg, ranked.riboflavin_mg,
    ranked.pyridoxine_mg, ranked.niacin_mg, ranked.vitamin_c_mg, ranked.source,
    ranked.source_edition, ranked.publication_year, ranked.source_url,
    ranked.reference_quantity_g, ranked.reference_basis, ranked.match_kind,
    ranked.relevance, count(*) over () as total_count
  from ranked
  order by ranked.relevance desc, ranked.name asc
  limit least(greatest(coalesce(p_limit, 20), 1), 50)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

create or replace function public.list_taco_categories()
returns table (category text)
language sql
stable
security invoker
set search_path = ''
as $$
  select distinct food.category
  from public.taco_foods as food
  where food.category is not null
  order by food.category;
$$;

create or replace function public.calculate_taco_food_nutrients(
  p_food_id uuid,
  p_quantity_g numeric
)
returns table (
  food_id uuid,
  food_name text,
  quantity_g numeric,
  energy_kcal numeric,
  protein_g numeric,
  carbohydrate_g numeric,
  lipid_g numeric,
  fiber_g numeric,
  sodium_mg numeric,
  source text,
  source_edition text,
  publication_year smallint,
  reference_basis text
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    food.id,
    food.name,
    p_quantity_g,
    round(food.energy_kcal * p_quantity_g / food.reference_quantity_g, 2),
    round(food.protein_g * p_quantity_g / food.reference_quantity_g, 2),
    round(food.carbohydrate_g * p_quantity_g / food.reference_quantity_g, 2),
    round(food.lipid_g * p_quantity_g / food.reference_quantity_g, 2),
    round(food.fiber_g * p_quantity_g / food.reference_quantity_g, 2),
    round(food.sodium_mg * p_quantity_g / food.reference_quantity_g, 2),
    food.source,
    food.source_edition,
    food.publication_year,
    food.reference_basis
  from public.taco_foods as food
  where food.id = p_food_id
    and p_quantity_g > 0
    and p_quantity_g <= 100000;
$$;

revoke all on function public.normalize_taco_search_text(text) from public, anon, authenticated;
grant execute on function public.normalize_taco_search_text(text) to authenticated, service_role;

revoke all on function public.search_taco_foods(text, text, integer, integer) from public, anon;
grant execute on function public.search_taco_foods(text, text, integer, integer) to authenticated, service_role;

revoke all on function public.list_taco_categories() from public, anon;
grant execute on function public.list_taco_categories() to authenticated, service_role;

revoke all on function public.calculate_taco_food_nutrients(uuid, numeric) from public, anon;
grant execute on function public.calculate_taco_food_nutrients(uuid, numeric) to authenticated, service_role;
